class_name Constants extends Node


const ENEMY = "ENEMY"
const PLAYER = "PLAYER"
const ENEMY_BUILDING = "ENEMY_BUILDING"
const PLAYER_BUILDING = "PLAYER_BUILDING"

const ANIMATION_IDLE = 'idle';
const ANIMATION_SHOOT = 'shoot';
#enum UNITTYPE {
	#ENEMY,
	#PLAYER,
	#ENEMY_BUILDING,
	#PLAYER_BUILDING
#}
#const  UNITTYPEGROUP = {
	#ENEMY = "ENEMY",
	#PLAYER = "PLAYER",
	#ENEMY_BUILDING = "ENEMY_BUILDING",
	#PLAYER_BUILDING = "PLAYER_BUILDING",
#}
